# /// script
# requires-python = "==3.11.*"
# dependencies = []
# ///
"""Appendix table: every distinct incident, from evidence/incidents.json. Usage: incidents_appendix.py OUT.tex

One row per distinct lesson coded as an incident (same_event_as = null), then the three
coordination events taken from commit history (hist-1..3). Descriptions and rules are the
already-scrubbed text in the evidence file (check_incidents.py refuses the client's and
people's names); this script only escapes LaTeX and orders the rows by date, then id.
Stdlib only; deterministic.
"""

import json
import sys
from pathlib import Path

EV = Path(__file__).resolve().parent.parent / "evidence"
data = json.loads((EV / "incidents.json").read_text())

ESC = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
       "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\^{}",
       "<": r"$<$", ">": r"$>$"}


def tex(s):
    return "".join(ESC.get(c, c) for c in str(s))


def cls(c):
    return tex(c).replace("/", "/\\allowbreak ")


def order(r):
    repo, _, n = r["id"].rpartition("-")
    return (r["date"], repo, int(n))


rows = sorted((r for r in data["lessons"]
               if r["same_event_as"] is None and r["kind"] == "incident"), key=order)
hist = sorted(data["coordination_events_from_history"], key=order)

copies = data["counts"]["times_each_original_was_copied"]
out = [r"% Generated by tables/incidents_appendix.py from evidence/incidents.json. Do not edit.",
       r"\begin{footnotesize}",
       r"\begin{longtable}{@{}>{\raggedright\arraybackslash}p{0.11\linewidth}>{\raggedright\arraybackslash}p{0.15\linewidth}>{\raggedright\arraybackslash}p{0.40\linewidth}>{\raggedright\arraybackslash}p{0.26\linewidth}@{}}",
       r"\caption{Every distinct incident in the eight lead playbooks (" + str(len(rows)) +
       r"), then three coordination events taken from studio's commit history. "
       r"Date as written in the lesson. Text is the evidence file's scrubbed summary. "
       r"A dagger marks a lesson that was later copied into other repositories (count in brackets).}"
       r"\label{tab:incident-list}\\",
       r"\toprule", r"Lesson, date & Cause class & What happened & Rule written back \\",
       r"\midrule", r"\endfirsthead",
       r"\toprule", r"Lesson, date & Cause class & What happened & Rule written back \\",
       r"\midrule", r"\endhead",
       r"\bottomrule", r"\endlastfoot"]
for r in rows:
    mark = (r"$^\dagger$[" + str(copies[r["id"]]) + "]") if r["id"] in copies else ""
    out.append(f"{tex(r['id'])}{mark}, {r['date'][5:]} & {cls(r['cause_class'])} & "
               f"{tex(r['description'])} & {tex(r['rule'])} \\\\")
out.append(r"\midrule")
for h in hist:
    ev = ", ".join(f"\\texttt{{{tex(s)}}}" for s in h["evidence"])
    out.append(f"{tex(h['id'])}, {h['date'][5:]} & {cls(h['cause_class'])} & "
               f"{tex(h['description'])} & (commit history: {ev}) \\\\")
out += [r"\end{longtable}", r"\end{footnotesize}", ""]

Path(sys.argv[1]).write_text("\n".join(out))
